aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet12
  description: Interface Created from platform_settings.structured_config
  switchport:
    enabled: true
hostname: platform_settings
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_security:
  entropy_sources:
    hardware: true
    haveged: true
    cpu_jitter: true
    hardware_exclusive: true
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
