aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: snmp-settings-2
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
service_routing_protocols_model: multi-agent
snmp_server:
  hosts:
  - host: 10.6.75.125
    version: 2c
    community: SNMP-COMMUNITY-2
  - host: 10.6.75.125
    vrf: SNMPVRF
    version: 2c
    community: SNMP-COMMUNITY-2
  - host: 10.6.75.126
    version: '3'
    users:
    - username: USER-WRITE
      authentication_level: auth
  - host: 10.6.75.127
    version: 2c
    community: SNMP-COMMUNITY-2
  - host: 10.6.75.127
    vrf: SNMPVRF
    version: 2c
    community: SNMP-COMMUNITY-2
  - host: 10.6.75.128
    version: '3'
    users:
    - username: USER-WRITE
      authentication_level: auth
  vrfs:
  - name: default
    enable: true
  - name: SNMPVRF
    enable: true
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan123
  description: Inband Management
  shutdown: false
  ip_address: 192.168.0.1/24
  mtu: 1500
  type: inband_mgmt
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4092
  name: INBAND_MGMT
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
