aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet3
  description: MLAG_UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B_Ethernet3
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B
  peer_interface: Ethernet3
  peer_type: mlag_peer
- name: Ethernet4
  description: MLAG_UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B_Ethernet4
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B
  peer_interface: Ethernet4
  peer_type: mlag_peer
- name: Ethernet1
  description: P2P_UPLINK-MLAG-STRUCTURED-CONFIG-SPINE1_Ethernet1
  shutdown: false
  mtu: 9214
  ip_address: 172.31.255.1/31
  pim:
    ipv4:
      sparse_mode: true
  peer: UPLINK-MLAG-STRUCTURED-CONFIG-SPINE1
  peer_interface: Ethernet1
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet5
  description: L2_UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1A_Ethernet1
  shutdown: false
  channel_group:
    id: 5
    mode: active
  peer: UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1A
  peer_interface: Ethernet1
  peer_type: l2leaf
- name: Ethernet6
  description: L2_UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1B_Ethernet1
  shutdown: false
  channel_group:
    id: 5
    mode: active
  peer: UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1B
  peer_interface: Ethernet1
  peer_type: l2leaf
hostname: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1A
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.3/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.254.3/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.200.105/24
  type: oob
  gateway: 192.168.200.5
metadata:
  platform: vEOS-LAB
mlag_configuration:
  domain_id: DC1_LEAF1
  local_interface: Vlan4094
  peer_address: 10.255.252.1
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B_Port-Channel3
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
- name: Port-Channel5
  description: L2_UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1_Port-Channel1
  shutdown: false
  mlag: 5
  storm_control:
    broadcast:
      level: '25'
    unknown_unicast:
      level: '25'
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: none
      native_vlan_tag: true
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
route_maps:
- name: RM-MLAG-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
    set:
    - origin incomplete
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65101'
  router_id: 192.168.255.3
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: MLAG-IPv4-UNDERLAY-PEER
    type: ipv4
    remote_as: '65101'
    description: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B
    next_hop_self: true
    send_community: all
    maximum_routes: 12000
    route_map_in: RM-MLAG-PEER-IN
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 10.255.251.1
    peer_group: MLAG-IPv4-UNDERLAY-PEER
    peer: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B
    description: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B_Vlan4093
  - ip_address: 172.31.255.0
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: UPLINK-MLAG-STRUCTURED-CONFIG-SPINE1
    description: UPLINK-MLAG-STRUCTURED-CONFIG-SPINE1_Ethernet1
  - ip_address: 192.168.255.1
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65001'
    peer: UPLINK-MLAG-STRUCTURED-CONFIG-SPINE1
    description: UPLINK-MLAG-STRUCTURED-CONFIG-SPINE1_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: MLAG-IPv4-UNDERLAY-PEER
      activate: true
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 4096
  no_spanning_tree_vlan: 4093-4094
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.5
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4093
  description: MLAG_L3
  shutdown: false
  ip_address: 10.255.251.0/31
  pim:
    ipv4:
      sparse_mode: true
  mtu: 9214
- name: Vlan4094
  description: mlag_peer_vlan_structured_config_override
  shutdown: false
  ip_address: 10.255.252.0/31
  mtu: 9214
  no_autostate: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4093
  name: MLAG_L3
  trunk_groups:
  - MLAG
  tenant: system
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1A_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      virtual_router_encapsulation_mac_address: mlag-system-id
